version: "3.1"

services:
  database:
    image: postgres:13-alpine
    ports:
      - "5432:5432"
    expose:
      - "5432:5432"
    environment:
      POSTGRES_DB: profiles
      POSTGRES_USER: profiles
      POSTGRES_PASSWORD: profiles
